### ISSUE TITLE
Support matchers not supported yet

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#70]
- request path
- request host
- request body

**Comment by jefferis** [comment]
@sckott is there likely to be support for request `body` with `http` any time soon? @SridharJagannathan

**Comment by sckott** [comment]
thanks for the ping @jefferis - have been working on this on this branch https://github.com/ropensci/vcr/tree/fix-request-body but stalled a bit with other work - can try to get this sorted soon - are you willing to test dev versions of this?

**Comment by SridharJagannathan** [comment]
@sckott, yes we can test your dev version of the implementation.

**Comment by jefferis** [comment]
Just to add, yes definitely very interested in this. We thought briefly that this already worked for crul but not httr. Matching on the body is the point of most interest for us as we need to be able to mock POST requests. FYI our first use case is this package https://github.com/jefferis/rcatmaid. We are also investigating the use of https://github.com/nealrichardson/httptest, but `vcr` might work better for cacheing a web server for reproducible data analysis.

**Comment by sckott** [comment]
Great, i'll ping when ready for testing

**Comment by sckott** [comment]
@SridharJagannathan @jefferis been working on this, rather complicated to deal with the various forms request bodies can take  - almost done - but leaving for vacation today - I expect to push a branch on the 24th or thereabouts with support for body requests

**Comment by sckott** [comment]
@jefferis @SridharJagannathan Changes are in the `fix-request-body` branch. If you have time, please give it a try, dev version of `webmockr` needed as well

```r
remotes::install_github("ropensci/webmockr@matchers-fix")
remotes::install_github("ropensci/vcr@fix-request-body")
```

e.g. each of these should work

```r
# method, uri, and body
use_cassette(name = "testing2", {
    res <- POST("https://httpbin.org/post", body = list(foo = "bar"))
}, match_requests_on = c("method", "uri", "body"))

# method and body
use_cassette(name = "testing2", {
    res <- POST("https://httpbin.org/post", body = list(foo = "bar"))
}, match_requests_on = c("method", "body"))

# just body
use_cassette(name = "testing2", {
    res <- POST("https://httpbin.org/post", body = list(foo = "bar"))
}, match_requests_on = "body")
```

Do let me know what you think, if you have any problems, etc.

**Comment by sckott** [comment]
this is working now, closing - see https://github.com/ropensci/rgbif/issues/365 for an example

**Comment by yogat3ch** [comment]
Hi @sckott, thank you for your work on this package! It was recommended to me as a solution for unit-tests in packages built around APIs. I'm currently implementing `vcr` across all the unit tests, but I'm running into an issue where `path` matching is necessary. The issue is described below:

I see that there are currently [matcher internal helper functions](https://github.com/ropensci/vcr/blob/7fe248b170f0f79ab14ffacea2c71f938c677c7e/R/match_helpers.R#L27) for host & path, but host and path matching methods don't appear to be implemented yet. 
The API I am building a package for requires secrets be sent as the `query` portion of a request. The secrets must be removed from the cassettes before pushing this package to Github/CRAN. When I remove the secrets the `uri` matching method will fail. The `uri` has all other request specific parameters as part of the `path`, so matching on `path` is what's needed for these unit tests to work.
Is there an expected completion date for `host` and `path` request matching? It seems pretty straightforward considering `host` and `path` generally have stricter formatting than do `query`, `header` or `body` segments of requests.
I just wanted to bring attention to this as it seems like it may have been forgotten since the issue was closed.

Thanks for your time & consideration!

**Comment by sckott** [comment]
Thanks for your note here @yogat3ch 

You're right, we didn't implement path and host yet. Main reason is I didn't have a use case myself yet, but I've been meaning to get it done. I'll have a look so I can give a better estimate of time

**Comment by sckott** [comment]
work on branch https://github.com/ropensci/vcr/tree/match-requests-host-path - should be close

**Comment by sckott** [comment]
@yogat3ch  done now - can you test it out?, restart R, then install `remotes::install_github("ropensci/vcr")`, then try matching on host, path, or host and path

**Comment by yogat3ch** [comment]
@sckott Totally understandable. 
That was a hyper expedited fix 🙌 Thank you so much!

|√ |  OK | F | W |  S | Context |
|--| ----| ---- | ---- | -----| ---- |
|√|  71    | 0 | 0  |  0 | Test all endpoints accessible from the polygon function [132.1 s] |

== Results ========================================================
Duration: 132.1 s

OK:       71
Failed:   0
Warnings: 0
Skipped:  0

It looks like all systems are go when matching by path with API keys removed from the queries!

**Comment by sckott** [comment]
@yogat3ch  Great, glad it works. Do let me know if any problems arise related to path/host matching

**Comment by yogat3ch** [comment]
Will do! No problems with multiple iterations thus far. Everything seems to be running smoothly!
